services:
    api_gateway:
        build: 
            context: ./api_gateway
            args:
                API_GATEWAY_PORT: 8080
                USERS_DB_SERVICE_NAME: users_db
                SECRET_KEY: SECRET
        ports: 
            - 8080:8080
        depends_on:
            - users_db
    users_db:
        image: mongo
        expose:
            - 27017
    products_service:
        build: 
            context: ./products_service
            args:
                PRODUCTS_SERVICE_PORT: 8081
                PRODUCTS_DB_SERVICE_NAME: products_db
        # expose:
        #     - 8081
        ports:
            - 8081:8081
        depends_on:
            - products_db
            - api_gateway
    products_db:
        image: mongo
        expose:
            - 27017
    mongo_express:
        image: mongo-express
        ports:
            - 27017:8081
        environment:
            - ME_CONFIG_MONGODB_URL=mongodb://users_db:27017
        depends_on:
            - users_db