services:
    api_gateway:
        build: 
            context: ./api_gateway
            args:
                API_GATEWAY_PORT: 8080
                USERS_DB_SERVICE_NAME: users_db
                SECRET_KEY: SECRET
        ports: 
            - 8080:8080
        depends_on:
            - users_db
    users_db:
        image: mongo
        expose:
            - 27017
    products_service:
        build:
            context: ./products_service
            args:
                PRODUCTS_SERVICE_PORT: 8081
                PRODUCTS_DB_SERVICE_NAME: products_db
        ports:
            - 8081:8081
        depends_on:
            - products_db
            - api_gateway
    products_db:
        image: mongo
        expose:
            - 27017
    carts-service:
        build:
            context: ./carts_service
            args:
                CARTS_SERVICE_PORT: 8082
                CARTS_DB_SERVICE_NAME: carts_db
                CARTS_DB_SERVICE_PORT: 5432
                CARTS_DB_USER: root
                CARTS_DB_PASSWORD: password
                CARTS_DB_NAME: carts_db
        ports:
            - 8082:8082
        depends_on:
            - carts_db
            - api_gateway
    carts_db:
        image: postgres
        shm_size: 128mb
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=carts_db
        expose:
            - 5432
    mongo_express:
        image: mongo-express
        ports:
            - 27017:8081
        environment:
            - ME_CONFIG_MONGODB_URL=mongodb://users_db:27017
        depends_on:
            - users_db