services:
    api_gateway:
        build: 
            context: ./api_gateway
            args:
                API_GATEWAY_PORT: 8080
                USERS_DB_SERVICE_NAME: users_db
                SECRET_KEY: SECRET
        ports: 
            - 8080:8080
        depends_on:
            - users_db
    users_db:
        image: mongo
        expose:
            - 27017
    products_service:
        build:
            context: ./products_service
            args:
                PRODUCTS_SERVICE_PORT: 8081
                PRODUCTS_DB_SERVICE_NAME: products_db
        ports:
            - 8081:8081
        depends_on:
            - mongo-init
            - api_gateway
    products_db:
        image: mongo
        hostname: products_db
        expose:
            - 27017
        command: mongod --replSet rs0 --bind_ip_all
    mongo-init:
        image: mongo
        depends_on:
            - products_db
        entrypoint: [
            "sh", "-c", 
            "sleep 5 && mongosh --host products_db:27017 --eval 'try { rs.initiate({_id: \"rs0\", members: [{ _id: 0, host: \"products_db:27017\" }]}); } catch (e) { if (!e.message.includes(\"already initialized\")) { throw e; } } (async () => { while(true) { await new Promise(r => setTimeout(r, 3600 * 1000)); } })()'"
        ]
    carts-service:
        build:
            context: ./carts_service
            args:
                CARTS_SERVICE_PORT: 8082
                CARTS_DB_SERVICE_NAME: carts_db
                CARTS_DB_SERVICE_PORT: 5432
                CARTS_DB_USER: root
                CARTS_DB_PASSWORD: password
                CARTS_DB_NAME: carts_db
        ports:
            - 8082:8082
        depends_on:
            - carts_db
            - api_gateway
    carts_db:
        image: postgres
        shm_size: 128mb
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=carts_db
        expose:
            - 5432
    profiles-service:
        build:
            context: ./profiles_service
            args:
                PROFILES_SERVICE_PORT: 8083
                PROFILES_DB_SERVICE_NAME: profiles_db
                PROFILES_DB_SERVICE_PORT: 5432
                PROFILES_DB_USER: root
                PROFILES_DB_PASSWORD: password
                PROFILES_DB_NAME: profiles_db
        ports:
            - 8083:8083
        depends_on:
            - profiles_db
            - api_gateway
    profiles_db:
        image: postgres
        shm_size: 128mb
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=profiles_db
        expose:
            - 5432
    orders-service:
        build:
            context: ./orders_service
            args:
                ORDERS_SERVICE_PORT: 8084
                ORDERS_DB_SERVICE_NAME: orders_db
        ports:
            - 8084:8084
        depends_on:
            - api_gateway
    orders_db:
        image: mongo
        hostname: orders_db
        expose:
            - 27017
    frontend-service:
        build:
            context: ./frontend_service
            args:
                - REACT_APP_GATEWAY=localhost
                - REACT_APP_GATEWAY_PORT=8080
        ports:
            - 4000:4000
        depends_on:
            - api_gateway
    mongo_express:
        image: mongo-express
        ports:
            - 27017:8081
        environment:
            - ME_CONFIG_MONGODB_URL=mongodb://orders_db:27017
        depends_on:
            - orders_db